#!/usr/bin/env python3
from __future__ import annotations

import csv
from pathlib import Path

COMMON_SOURCE = {
    "source_type": "制度",
    "source_title": "高等学校实验室安全规范",
    "source_org": "教育部",
    "source_version": "2024",
    "source_date": "2024-09-12",
    "source_url": "https://www.moe.gov.cn/srcsite/A04/s7051/202409/t20240912_1151131.html",
    "last_updated": "2026-03-31",
    "reviewer": "",
    "status": "draft",
    "language": "zh-CN",
}

NEW_ENTRIES = [
    {
        "id": "KB-1049",
        "title": "化学品溅入眼睛后的首要处置",
        "category": "化学",
        "subcategory": "事故应急卡片",
        "lab_type": "化学",
        "risk_level": "5",
        "hazard_types": "化学暴露;眼部飞溅;应急处置",
        "scenario": "化学品飞溅进入眼睛后的第一时间处置",
        "question": "化学品溅入眼睛后第一步应该做什么？",
        "answer": "第一步不是找老师，也不是先判断药品种类，而是立刻持续冲洗。应立即使用洗眼器或大量流动清水冲洗眼部，持续至少 15 分钟，并尽快通知周围人员协助就医。",
        "steps": "立即到洗眼器处持续冲洗;撑开上下眼睑让水流充分接触眼球;如佩戴隐形眼镜尽快取下;通知同伴和实验室负责人;携带化学品标签或 SDS 信息就医",
        "ppe": "护目镜;面屏;实验服;适配的防化手套",
        "forbidden": "禁止延迟冲洗去查资料;禁止自行点眼药或加中和液;禁止症状稍缓后继续实验",
        "disposal": "污染纸巾和一次性用品按化学污染废弃物处理",
        "first_aid": "持续冲洗至少 15 分钟后尽快就医",
        "emergency": "立即通知实验室负责人，必要时启动校内医疗应急流程",
        "legal_notes": "洗眼器应处于可用状态并纳入日常点检",
        "references": "高等学校实验室安全规范; 化学品暴露应急处置 SOP",
        "tags": "化学品入眼;眼睛飞溅;洗眼器;冲洗15分钟;眼部暴露;化学飞溅;eye splash;eyewash",
    },
    {
        "id": "KB-1050",
        "title": "实验室小火何时必须立即撤离",
        "category": "通用",
        "subcategory": "事故应急卡片",
        "lab_type": "通用",
        "risk_level": "5",
        "hazard_types": "火灾;撤离;应急处置",
        "scenario": "实验室初起火灾与立即撤离边界判断",
        "question": "实验室起小火时，什么时候必须立即撤离？",
        "answer": "只要火势不再处于可控的小范围初起状态，或疏散路线不清晰，就应立即撤离。若伴随浓烟、未知燃烧物、爆炸风险、气瓶受热或操作者未受过灭火训练，不应继续停留处置。",
        "steps": "先警示周围人员;在确保安全的前提下切断气源和电源;确认出口畅通;仅在受训且火势可控时使用正确灭火器;无法迅速控制时立即撤离并报警",
        "ppe": "撤离优先，不以寻找额外 PPE 为前提",
        "forbidden": "禁止在浓烟中逗留;禁止背对出口灭火;禁止对未知燃烧物随意选用灭火器",
        "disposal": "灭火残留物按事故污染废弃物处理",
        "first_aid": "热灼伤应冷却处理，吸入烟雾应尽快转移至空气新鲜处并就医",
        "emergency": "按单位消防预案启动报警和疏散流程",
        "legal_notes": "初起火灾处置应建立在培训和演练基础上",
        "references": "高等学校实验室消防安全管理规范; 实验室消防应急预案",
        "tags": "实验室着火;小火撤离;什么时候撤离;火灾应急;浓烟;爆炸风险;fire evacuation;small lab fire",
    },
    {
        "id": "KB-1051",
        "title": "触电后为什么不能直接用手拉人",
        "category": "通用",
        "subcategory": "事故应急卡片",
        "lab_type": "机电",
        "risk_level": "5",
        "hazard_types": "触电;电气事故;应急处置",
        "scenario": "触电事故的第一时间处置边界",
        "question": "有人触电后为什么不能直接用手把他拉开？",
        "answer": "因为在电源未隔离前，伤者和设备可能仍然带电，徒手拉人会让施救者也成为触电者。正确原则是先断电、后接触；无法立刻断电时，也必须使用绝缘物将人员与电源隔离。",
        "steps": "优先切断电源或按下急停;无法断电时使用绝缘物隔离;呼叫急救并评估呼吸意识;保护现场并禁止重新送电;事故后进行设备复盘",
        "ppe": "绝缘手套;绝缘工具;绝缘鞋",
        "forbidden": "禁止未断电徒手拉人;禁止向带电设备泼水;禁止事故后立即重新开机测试",
        "disposal": "损坏的带电部件按电气故障件管理",
        "first_aid": "断电后按急救流程处理并尽快就医",
        "emergency": "触电事故应立即升级上报并保留现场",
        "legal_notes": "电气事故处置必须遵循先隔离能量再接触伤者的原则",
        "references": "高等学校实验室安全规范; 实验室电气安全 SOP",
        "tags": "触电;先断电;不能直接拉;绝缘物;电气应急;electric shock;cut power first",
    },
    {
        "id": "KB-1052",
        "title": "未知化学品泄漏时先做什么",
        "category": "化学",
        "subcategory": "事故应急卡片",
        "lab_type": "化学",
        "risk_level": "5",
        "hazard_types": "化学泄漏;未知物质;应急处置",
        "scenario": "未知液体或未知化学品外泄的首要动作",
        "question": "遇到未知化学品泄漏时，第一步是先擦掉吗？",
        "answer": "不是。第一步应是停止附近操作并隔离现场，而不是立即上手清理。未知化学品意味着你无法确定其毒性、挥发性和相容性，在风险未识别前，不应贸然擦拭、冲水或移动泄漏物。",
        "steps": "停止附近实验和点火源;隔离泄漏区域;识别容器和标签信息;判断是否属于本人训练范围;确认处置路径后再使用吸附和收集工具",
        "ppe": "护目镜;防化手套;实验服;必要时按 SOP 增加呼吸防护",
        "forbidden": "禁止徒手接触;禁止未确认就直接冲入下水道;禁止在泄漏附近继续加热或明火操作",
        "disposal": "污染吸附材料和清理工具按危废收集",
        "first_aid": "如已暴露人体，按暴露部位执行冲洗和就医流程",
        "emergency": "大面积、强挥发或身份未知的泄漏应立即升级处置",
        "legal_notes": "未知化学品按高风险泄漏事件处理",
        "references": "高等学校实验室安全规范; 化学品泄漏应急 SOP",
        "tags": "未知泄漏;未知化学品;先隔离;不要先擦;spill isolation;unknown chemical",
    },
    {
        "id": "KB-1053",
        "title": "高风险实验审批重点审查内容",
        "category": "通用",
        "subcategory": "高风险审批",
        "lab_type": "通用",
        "risk_level": "4",
        "hazard_types": "审批;风险评估;管理",
        "scenario": "高风险实验审批的核心审查项",
        "question": "高风险实验审批一般重点审查哪些内容？",
        "answer": "高风险审批不是只看导师是否同意，而是审查整套前置条件是否完整。重点通常包括实验目的与步骤是否明确、危险源识别是否充分、风险评估是否完成、控制措施和 PPE 是否匹配、操作者是否受训授权、是否需要双人作业，以及应急预案和废弃物路径是否清晰。",
        "steps": "提交实验方案和 SOP;补充风险评估表;明确控制措施与应急方案;核验人员资质和准入;审批通过后再排期执行",
        "ppe": "在审批阶段就应明确 PPE 标准，而不是临场决定",
        "forbidden": "禁止无风险评估先审批;禁止用口头同意替代正式审查;禁止审批后擅自扩大实验边界",
        "disposal": "审批阶段应同时确认废液和危险废物去向",
        "first_aid": "审批表中应包含主要事故情形的应急要点",
        "emergency": "审批未完成前不得进入开工状态",
        "legal_notes": "高风险实验应留痕管理并落实前置审查",
        "references": "高等学校实验室安全规范; 实验室安全分级分类管理办法",
        "tags": "高风险审批;审批审什么;审批重点;风险评估;前置审查;approval checklist;hazard review",
    },
    {
        "id": "KB-1054",
        "title": "审批通过后为什么还要双人复核",
        "category": "通用",
        "subcategory": "高风险审批",
        "lab_type": "通用",
        "risk_level": "4",
        "hazard_types": "审批;双人复核;监护",
        "scenario": "审批与现场复核的关系",
        "question": "高风险实验审批通过以后，还需要双人复核吗？",
        "answer": "通常仍然需要。审批解决的是计划层面是否允许开展，双人复核解决的是现场条件此刻是否真正满足。很多事故并不是没有审批，而是现场执行时出现标签错误、联锁未开、PPE 不合规、人员状态不适合等问题，所以审批不能替代现场双人复核。",
        "steps": "按审批意见准备实验;由第二人复核关键项;确认设备、试剂、PPE 和应急设施状态;全部通过后再启动",
        "ppe": "按审批要求逐项落实，不得临时削减",
        "forbidden": "禁止以审批通过为理由跳过现场复核;禁止单人自行确认全部关键项",
        "disposal": "如复核发现废弃物路径不清，应先整改再开工",
        "first_aid": "复核阶段应再次确认事故处置资源可用",
        "emergency": "发现关键项异常时应立即暂停开工并回退整改",
        "legal_notes": "高风险实验应同时满足书面审批和现场条件确认",
        "references": "高等学校实验室安全规范; 实验室安全分级分类管理办法",
        "tags": "双人复核;审批通过后;还要复核吗;buddy check;现场复核;secondary review",
    },
    {
        "id": "KB-1055",
        "title": "临时改步骤改试剂是否需要重新审批",
        "category": "通用",
        "subcategory": "高风险审批",
        "lab_type": "通用",
        "risk_level": "4",
        "hazard_types": "变更管理;审批;风险重评",
        "scenario": "高风险实验执行中的临时变更",
        "question": "实验过程中如果临时改步骤、改试剂或改设备，需要重新审批吗？",
        "answer": "如果变更会影响危险源、风险等级、控制措施、操作边界或废弃物路径，就应视为实质性变更，原则上需要重新评估并重新审批。很多事故正是由未经评估的小改动触发的，所以不能把“只改一点点”当成跳过审批的理由。",
        "steps": "先暂停执行;比较变更前后的危险源和控制条件;如影响风险边界则重新评估并提交审批;批准后再继续",
        "ppe": "变更后同步检查 PPE 是否仍然适配",
        "forbidden": "禁止边做边改且不留痕;禁止实质性变更不重新评估;禁止口头通知代替正式变更记录",
        "disposal": "变更后若产生新型废物，应重新确认分类和去向",
        "first_aid": "变更后应同步更新可能事故类型与急救要点",
        "emergency": "临时变更导致风险不确定时，应回退到安全状态",
        "legal_notes": "高风险实验应实施变更管理和再评估",
        "references": "高等学校实验室安全规范; 实验室安全分级分类管理办法",
        "tags": "改步骤;改试剂;改设备;重新审批;变更管理;change control;风险重评;procedure change",
    },
    {
        "id": "KB-1056",
        "title": "夜间或节假日能否开展高风险实验",
        "category": "通用",
        "subcategory": "高风险审批",
        "lab_type": "通用",
        "risk_level": "4",
        "hazard_types": "夜间实验;节假日实验;审批",
        "scenario": "夜间和节假日开展高风险实验的边界",
        "question": "夜间或者节假日可以安排高风险实验吗？",
        "answer": "原则上应从严控制。只有在审批明确允许、双人值守、应急资源可用、导师或管理链路在线、现场条件稳定的情况下，才可能安排。若任何一项前置条件不足，就不应在夜间或节假日开展高风险实验。",
        "steps": "核查是否属于必须安排的任务;确认审批意见覆盖夜间或节假日场景;落实双人值守和通讯链路;确认应急物资和保卫值班可用;条件不满足则改期",
        "ppe": "与日间标准一致，不因时段降低要求",
        "forbidden": "禁止以赶进度为由默认夜间开工;禁止单人夜间开展高风险实验;禁止无值班支撑时强行开展",
        "disposal": "夜间结束后不得将危险废物随意滞留于无管理状态",
        "first_aid": "应确认夜间医疗和应急联络方式可达",
        "emergency": "通讯链路、值班或门禁异常时应立即取消计划",
        "legal_notes": "夜间和节假日实验需满足更严格的审批和监护要求",
        "references": "高等学校实验室安全规范; 实验室值班与高风险实验管理制度",
        "tags": "夜间实验;节假日实验;能不能做;高风险实验夜间;after-hours;working alone at night",
    },
    {
        "id": "KB-1057",
        "title": "培训未通过能否独立开展高风险实验",
        "category": "通用",
        "subcategory": "培训考核",
        "lab_type": "通用",
        "risk_level": "4",
        "hazard_types": "培训;准入;授权",
        "scenario": "培训成绩与高风险实验准入之间的关系",
        "question": "实验室培训没有通过，还能独立开展高风险实验吗？",
        "answer": "不能。培训是否通过直接关联准入资格。未通过培训说明对 SOP、风险边界、应急处置或禁止事项掌握不足，此时不应获得独立开展高风险实验的授权，应先补训、复测并通过后再进入独立操作阶段。",
        "steps": "暂停独立上机或独立开工资格;查看错题和薄弱类别;完成补训和复测;通过后再恢复授权",
        "ppe": "培训未通过并不会降低现场风险，因此 PPE 要求不能打折",
        "forbidden": "禁止培训未通过人员独立开展高风险实验;禁止以口头承诺代替考核通过;禁止代答代考",
        "disposal": "培训记录和准入记录应同步留档",
        "first_aid": "补训内容应覆盖主要事故类型的急救流程",
        "emergency": "若发现未授权人员已在独立操作，应立即叫停并上报",
        "legal_notes": "培训考核结果应与岗位授权和设备准入联动",
        "references": "高等学校实验室安全规范; 实验室人员准入与培训制度",
        "tags": "培训没通过;不能独立实验;高风险准入;补训;training pass;authorization;独立操作",
    },
    {
        "id": "KB-1058",
        "title": "新成员首次进实验室前要完成哪些培训",
        "category": "通用",
        "subcategory": "培训考核",
        "lab_type": "通用",
        "risk_level": "3",
        "hazard_types": "培训;新成员;准入",
        "scenario": "新成员入室前的基础培训清单",
        "question": "新成员第一次进入实验室前，一般要先完成哪些培训？",
        "answer": "至少应完成实验室通用安全教育、所在实验室 SOP 学习、危险源与 PPE 基础、废弃物分类、应急设施位置与报警流程，以及与本人任务相关的专项培训。进入高风险区域前，还应完成设备上岗或专项授权培训。",
        "steps": "完成通用安全教育;学习本实验室规章和 SOP;熟悉危险源、PPE 与废弃物要求;识别应急设施和疏散路线;需要时完成专项设备培训",
        "ppe": "培训中应明确不同任务对应的 PPE 基线要求",
        "forbidden": "禁止未经培训直接入室操作;禁止只看视频不做现场确认;禁止将签到视为培训完成",
        "disposal": "培训中应包含危废暂存和交接流程",
        "first_aid": "入室前应掌握基础急救和报警方式",
        "emergency": "新成员应能独立指出洗眼器、灭火器和出口位置",
        "legal_notes": "新成员培训应与准入记录绑定留痕",
        "references": "高等学校实验室安全规范; 实验室新成员准入制度",
        "tags": "新成员培训;首次进实验室;入门培训;专项培训;onboarding;lab induction;准入培训",
    },
    {
        "id": "KB-1059",
        "title": "错题本和培训记录除了留档还有什么用",
        "category": "通用",
        "subcategory": "培训考核",
        "lab_type": "通用",
        "risk_level": "2",
        "hazard_types": "培训;错题复盘;持续改进",
        "scenario": "培训记录在持续改进中的作用",
        "question": "实验室培训里的错题本和培训记录，除了留档还有什么意义？",
        "answer": "它们的价值不只是证明“培训做过了”，更重要的是发现谁在哪些类别上反复出错，从而安排定向补训、调整题库、优化 SOP 表达，并把培训结果真正接入准入管理。错题本是风险画像，培训记录是持续改进依据。",
        "steps": "统计错题类别;识别高频薄弱点;安排定向补训;修订题库和操作提示;将结果反馈到准入与监督机制",
        "ppe": "若某类 PPE 相关题目频繁出错，应增加现场示教",
        "forbidden": "禁止把培训记录当成纯行政台账;禁止只记录分数不看错题分布",
        "disposal": "不涉及",
        "first_aid": "高频错题若涉及应急，应优先补训",
        "emergency": "连续错在高风险题目上时，应临时限制相关操作权限",
        "legal_notes": "培训档案应服务于能力改进而非只为留痕",
        "references": "高等学校实验室安全规范; 实验室培训与能力评估制度",
        "tags": "错题本;培训记录;除了留档;持续改进;mistake review;training log;补训",
    },
    {
        "id": "KB-1060",
        "title": "培训通过率持续偏低时管理员先做什么",
        "category": "通用",
        "subcategory": "培训考核",
        "lab_type": "通用",
        "risk_level": "3",
        "hazard_types": "培训管理;统计分析;持续改进",
        "scenario": "培训通过率低时的管理动作",
        "question": "如果实验室培训通过率一直偏低，管理员应该先做什么？",
        "answer": "第一步不是简单提高难度或重复考试，而是先看错题分布和薄弱类别，判断是题目表述问题、培训内容不到位、现场规则和题库不一致，还是新成员结构变化导致。只有先定位原因，后续补训和制度修订才有效。",
        "steps": "拉取通过率和错题类别统计;定位薄弱知识点;核对题库与现行 SOP 是否一致;组织针对性补训;复测后再看是否改善",
        "ppe": "若 PPE 类题目错误集中，应增加实操检查环节",
        "forbidden": "禁止只看总通过率不看原因;禁止长期使用过期题库;禁止培训与现场规则脱节",
        "disposal": "不涉及",
        "first_aid": "若急救类题目通过率低，应优先补齐",
        "emergency": "连续两轮低通过率时应触发专项整改",
        "legal_notes": "培训通过率应与整改机制和看板联动",
        "references": "高等学校实验室安全规范; 实验室培训与能力评估制度",
        "tags": "培训通过率低;管理员先做什么;错题分析;题库复核;training pass rate;weak category",
    },
]


def main() -> None:
    repo_root = Path(__file__).resolve().parents[2]
    kb_path = repo_root / "knowledge_base_curated.csv"
    with kb_path.open("r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        rows = list(reader)
        fieldnames = reader.fieldnames or []

    normalized_entries = []
    for entry in NEW_ENTRIES:
        merged = dict(COMMON_SOURCE)
        merged.update(entry)
        normalized_entries.append(merged)

    keep_ids = {entry["id"] for entry in normalized_entries}
    preserved_rows = [row for row in rows if (row.get("id") or "").strip() not in keep_ids]
    merged_rows = preserved_rows + [{key: entry.get(key, "") for key in fieldnames} for entry in normalized_entries]

    with kb_path.open("w", encoding="utf-8-sig", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(merged_rows)

    print(f"upserted={len(normalized_entries)} total={len(merged_rows)}")


if __name__ == "__main__":
    main()
