#!/usr/bin/env python3
"""Append new hand-curated KB entries to knowledge_base_curated.csv."""
import csv
from pathlib import Path

KB_FIELDNAMES = [
    "id","title","category","subcategory","lab_type","risk_level","hazard_types",
    "scenario","question","answer","steps","ppe","forbidden","disposal",
    "first_aid","emergency","legal_notes","references","source_type",
    "source_title","source_org","source_version","source_date","source_url",
    "last_updated","reviewer","status","tags","language",
]

new_entries = [
    {
        "id": "KB-1026", "title": "辐射安全-辐射工作准入要求", "category": "辐射",
        "subcategory": "辐射防护", "lab_type": "辐射", "risk_level": "4",
        "hazard_types": "辐射;放射性", "scenario": "辐射实验室准入与防护要求",
        "question": "进入辐射实验室需要哪些资质和防护要求？",
        "answer": "辐射工作人员必须通过环保部门组织的培训，取得《辐射安全与防护培训合格证书》后方可上岗。进行放射性实验前必须由导师进行防护知识培训和安全教育。操作时须采取屏蔽、距离、时间三大防护原则，正确佩戴个人剂量计并接受定期个人剂量监测。购置放射源、射线装置须经学校审批，新建放射性工作场所须经环保部门批准。",
        "steps": "取得辐射安全培训合格证;接受导师防护培训;佩戴个人剂量计;严格按SOP操作;定期剂量监测",
        "ppe": "个人剂量计;防护服;手套;必要时铅围裙",
        "forbidden": "禁止无证上岗;禁止独自操作高风险放射源;禁止在非指定区域操作",
        "disposal": "放射性废物按国家标准分类存放，交有资质机构处置",
        "first_aid": "发生放射性污染立即疏散，通知辐射安全负责人并就医",
        "emergency": "放射源丢失或意外照射立即上报学校和环保部门",
        "legal_notes": "遵守《放射性同位素与射线装置安全和防护条例》",
        "references": "北京大学医学部实验室安全手册;教育部《高等学校实验室安全规范》",
        "source_type": "制度", "source_title": "高等学校实验室安全规范（辐射安全部分）",
        "source_org": "教育部/北京大学医学部", "source_version": "2023",
        "source_date": "2023-02-21",
        "source_url": "https://www.cernet.edu.cn/ke_yan_yu_fa_zhan/gai_kuang/xin_wen_gong_gao/202302/t20230221_2301697.shtml",
        "last_updated": "2026-03-15", "reviewer": "", "status": "draft",
        "tags": "辐射;放射性;防护;准入", "language": "zh-CN",
    },
    {
        "id": "KB-1027", "title": "辐射安全-放射性污染应急处置", "category": "辐射",
        "subcategory": "辐射应急", "lab_type": "辐射", "risk_level": "5",
        "hazard_types": "辐射;放射性污染", "scenario": "放射性污染或意外照射",
        "question": "发生放射性污染或意外照射怎么办？",
        "answer": "发生放射性同位素丢失、意外照射或放射性污染事故时，应立即疏散周围人员并隔离污染区域，禁止无关人员进入。皮肤污染应立即用流水和肥皂清洗，眼部污染用大量清水冲洗。第一时间通知实验室辐射安全负责人和学校主管部门，根据事故级别逐级上报至生态环境部门。保留事故现场，配合专业人员勘查处置。",
        "steps": "疏散人员并隔离区域;皮肤或眼部污染立即冲洗;通知辐射安全负责人;按级别上报环保部门;配合专业机构处置",
        "ppe": "防护服;手套;个人剂量计;必要时铅围裙",
        "forbidden": "禁止独自处置高风险污染;禁止自行丢弃放射性废物",
        "disposal": "放射性废物由有资质专业机构统一处置",
        "first_aid": "皮肤污染用流水清洗；内照射或大剂量照射立即就医",
        "emergency": "立即疏散隔离，逐级上报，启动辐射事故应急预案",
        "legal_notes": "遵守《放射性同位素与射线装置安全和防护条例》，须在1小时内上报",
        "references": "北京大学医学部实验室安全手册",
        "source_type": "应急预案", "source_title": "放射性事故应急处置规范",
        "source_org": "教育部/高校通用", "source_version": "2023",
        "source_date": "2023-02-21",
        "source_url": "https://reagent.bjmu.edu.cn/file/20230414134400495_%E5%AE%9E%E9%AA%8C%E5%AE%A4%E5%AE%89%E5%85%A8%E6%89%8B%E5%86%8C%E5%8D%B0%E5%88%B7%E7%89%8820210610.pdf",
        "last_updated": "2026-03-15", "reviewer": "", "status": "draft",
        "tags": "辐射;放射性污染;应急;事故处置", "language": "zh-CN",
    },
    {
        "id": "KB-1028", "title": "激光安全-激光器操作规范", "category": "电气",
        "subcategory": "激光安全", "lab_type": "光学", "risk_level": "4",
        "hazard_types": "激光;强光辐射", "scenario": "激光器操作与防护",
        "question": "使用激光器时有哪些安全注意事项？",
        "answer": "操作激光器时严禁用眼睛直视激光束，包括反射光。不可见的红外激光束尤其危险，须了解光路布局，避免使头部处于激光束水平面。禁止在激光路径上放置易燃物（如黑色纸张、布料、皮革）。操作时摘除所有带反光面的首饰等物品。激光实验室须配备安全屏蔽设施，功率较大的激光器须有互锁装置和防护罩，设置黄色安全警示线。使用前须经过专门培训并留有培训记录。",
        "steps": "检查防护设施与互锁装置;清除光路上的易燃物;摘除反光饰物;佩戴对应波长激光护目镜;按SOP开机并确认光路安全",
        "ppe": "激光专用防护目镜（对应波长）;实验服",
        "forbidden": "禁止直视激光束;禁止在光路附近放易燃物;禁止未培训上岗",
        "disposal": "损坏的光学元件按一般固废处理",
        "first_aid": "激光伤害眼睛立即用清水冲洗并就医，皮肤灼伤按热灼伤处理",
        "emergency": "设备故障立即断电并报告实验室管理员",
        "legal_notes": "遵守GBZ 2.2激光辐射职业接触限值；实验室接触强度不得超过规定限值",
        "references": "上海交通大学中英国际低碳学院实验室安全与管理规范;北京交通大学实验室安全管理办法",
        "source_type": "SOP", "source_title": "激光安全操作规范",
        "source_org": "上海交通大学/高校通用", "source_version": "2021",
        "source_date": "2021-01-01",
        "source_url": "https://lcc.sjtu.edu.cn/Assets/userfiles/sys_eb538c1c-65ff-4e82-8e6a-a1ef01127fed/files/sysgl/%E4%B8%8A%E6%B5%B7%E4%BA%A4%E9%80%9A%E5%A4%A7%E5%AD%A6%E4%B8%AD%E8%8B%B1%E5%9B%BD%E9%99%85%E4%BD%8E%E7%A2%B3%E5%AD%A6%E9%99%A2%E5%AE%9E%E9%AA%8C%E5%AE%A4%E5%AE%89%E5%85%A8%E4%B8%8E%E7%AE%A1%E7%90%86%E8%A7%84%E8%8C%83.pdf",
        "last_updated": "2026-03-15", "reviewer": "", "status": "draft",
        "tags": "激光;光学;强光;防护", "language": "zh-CN",
    },
    {
        "id": "KB-1029", "title": "低温安全-液氮操作规范", "category": "化学",
        "subcategory": "低温安全", "lab_type": "通用", "risk_level": "4",
        "hazard_types": "低温;冻伤;窒息", "scenario": "液氮取用与储存操作",
        "question": "使用液氮时需要注意什么？",
        "answer": "液氮温度极低（-196摄氏度），可造成严重冻伤，且快速蒸发会使密闭空间严重缺氧。使用前确认房间门窗打开、通风良好；确认皮肤干燥，佩戴绝缘防护手套和防护面罩。往容器注入液氮时动作缓慢，避免飞溅。转移液氮时须使用专用液氮罐，禁止用普通密封容器存放。液氮存储区须安装氧气浓度报警器并定期检测。禁止通过客用电梯运送液氮。",
        "steps": "确认通风良好;佩戴绝缘手套和护目镜;缓慢注入液氮;检查氧气报警器状态;安全转移至专用液氮罐",
        "ppe": "绝缘防护手套;护目镜或防护面罩;实验服",
        "forbidden": "禁止用密封容器存放;禁止在密闭空间大量使用;禁止通过客梯运送;禁止裸手接触",
        "disposal": "少量液氮可在通风良好处自然蒸发，容器按普通废物处理",
        "first_aid": "冻伤部位用温水（37-40摄氏度）缓慢复温，禁止摩擦，立即就医；缺氧立即转移至通风处",
        "emergency": "大量泄漏立即疏散，启动应急预案，通知管理人员",
        "legal_notes": "遵守实验室特种设备管理规定",
        "references": "宁夏医科大学液氮罐安全使用及管理办法;中国地质大学（北京）液氮操作规程",
        "source_type": "SOP", "source_title": "液氮安全操作规程",
        "source_org": "宁夏医科大学/高校通用", "source_version": "2020",
        "source_date": "2020-12-03",
        "source_url": "http://www.nxmu.edu.cn/lnjbzdsys/info/1094/1283.htm",
        "last_updated": "2026-03-15", "reviewer": "", "status": "draft",
        "tags": "液氮;低温;冻伤;窒息", "language": "zh-CN",
    },
    {
        "id": "KB-1030", "title": "机械安全-离心机操作规范", "category": "通用",
        "subcategory": "机械安全", "lab_type": "通用", "risk_level": "3",
        "hazard_types": "机械;高速旋转", "scenario": "离心机安全使用",
        "question": "使用离心机有哪些安全规定？",
        "answer": "使用离心机时，离心管必须配对平衡，用天平称量确认两侧质量相等；不对称放置可能导致机身剧烈振动乃至损坏。启动前先盖好盖子，从低速开始逐渐调至目标速度。离心过程中禁止打开盖子，必须等到转子完全停止后才能开盖取样。超速会导致离心管破裂，操作前确认所用离心管的最高转速额定值。出现异常振动或噪声立即停机并报告。",
        "steps": "天平称量确认平衡;对称放置;盖好盖子;从低速启动;等待完全停止后再开盖",
        "ppe": "护目镜;实验服",
        "forbidden": "禁止不平衡放置;禁止运转时开盖;禁止超过额定转速",
        "disposal": "离心管按内容物类型分类处置",
        "first_aid": "离心管破裂造成暴露按相应物质的急救措施处理",
        "emergency": "异常振动立即切断电源，报告设备管理员检修",
        "legal_notes": "遵守实验室仪器设备安全操作规程",
        "references": "上海交通大学生命科学技术学院实验室常见危险设备操作注意事项;中国药科大学实验室安全手册",
        "source_type": "SOP", "source_title": "离心机安全操作SOP",
        "source_org": "上海交通大学/高校通用", "source_version": "2023",
        "source_date": "2023-01-01",
        "source_url": "https://life.sjtu.edu.cn/Data/View/6077",
        "last_updated": "2026-03-15", "reviewer": "", "status": "draft",
        "tags": "离心机;机械;高速旋转;平衡", "language": "zh-CN",
    },
    {
        "id": "KB-1031", "title": "设备安全-高压灭菌锅操作", "category": "生物",
        "subcategory": "高温高压设备", "lab_type": "生物", "risk_level": "3",
        "hazard_types": "高压;高温;蒸汽", "scenario": "高压灭菌器（高压锅）使用",
        "question": "高压灭菌锅使用时需要注意什么？",
        "answer": "高压灭菌锅须由经过专项培训的人员操作，全程专人看管，不得擅自离开。操作前检查水位，防止干烧损坏电热管。有压力时联锁手柄不可强制打开，绝对禁止带压开门。液体灭菌结束后须慢速放汽，等液体温度降至安全值后方可开门；开门时操作人员须站在两侧，缓慢开盖，防止残余蒸汽喷出烫伤。灭菌结束后须在内容物上粘贴生物危害标识。",
        "steps": "检查水位;放入待灭菌物;设置正确参数;全程看管;放汽降温后开门;贴生物危害标识",
        "ppe": "耐热手套;护目镜;实验服",
        "forbidden": "禁止带压强制开门;禁止擅自离岗;禁止用于不耐高温物品",
        "disposal": "灭菌后废弃物按生物危废处理",
        "first_aid": "蒸汽烫伤立即用凉水冷却20分钟，就医",
        "emergency": "异常升压或泄漏立即断电并疏散，联系维修人员",
        "legal_notes": "高压灭菌锅属特种设备，须定期检测",
        "references": "上海交通大学生命科学技术学院实验室常见危险设备操作注意事项",
        "source_type": "SOP", "source_title": "高压灭菌锅操作SOP",
        "source_org": "上海交通大学/高校通用", "source_version": "2023",
        "source_date": "2023-01-01",
        "source_url": "https://life.sjtu.edu.cn/Data/View/6077",
        "last_updated": "2026-03-15", "reviewer": "", "status": "draft",
        "tags": "高压灭菌;灭菌锅;高温;蒸汽", "language": "zh-CN",
    },
    {
        "id": "KB-1032", "title": "消防-灭火器选择与使用", "category": "通用",
        "subcategory": "消防设备", "lab_type": "通用", "risk_level": "4",
        "hazard_types": "火灾;消防", "scenario": "实验室初起火灾处置与灭火器选择",
        "question": "实验室起火了，应该选择哪种灭火器？如何使用？",
        "answer": "灭火器选择须根据火灾类型：普通固体火灾（纸、木、布）可用干粉或水；化学试剂或有机溶剂火灾用干粉灭火器；电气火灾须先断电再灭火，使用干粉或二氧化碳灭火器，严禁用水或泡沫灭火器；锂电池火灾用干砂或专用锂电池灭火器，禁止直接用水喷。使用手提式干粉灭火器的步骤：拔出保险销→对准火焰根部→压下手柄→左右扫射。不能控制时立即撤离并拨打119。",
        "steps": "判断火灾类型;选择对应灭火器;拔保险销;对准火焰根部;压手柄喷射;无法控制立即撤离报警",
        "ppe": "避免吸入灭火剂烟雾",
        "forbidden": "禁止向电气火灾用水或泡沫;禁止背对出口扑救;禁止冒险进入浓烟区",
        "disposal": "使用过的灭火器送维修站检验充装",
        "first_aid": "吸入烟雾不适及时转移至通风处；烧伤用凉水冷却并就医",
        "emergency": "无法控制立即撤离，拨打119，并到路口引导消防车",
        "legal_notes": "遵守《高等学校实验室消防安全管理规范》JY/T 0616—2023",
        "references": "教育部《高等学校实验室消防安全管理规范》JY/T 0616—2023;上海科技大学EHS消防规范",
        "source_type": "制度", "source_title": "高等学校实验室消防安全管理规范",
        "source_org": "教育部", "source_version": "JY/T 0616—2023",
        "source_date": "2023-06-26",
        "source_url": "https://sysglc.ntu.edu.cn/2024/0326/c8767a230277/page.htm",
        "last_updated": "2026-03-15", "reviewer": "", "status": "draft",
        "tags": "灭火器;消防;火灾;干粉;二氧化碳", "language": "zh-CN",
    },
    {
        "id": "KB-1033", "title": "应急-火灾疏散逃生规范", "category": "通用",
        "subcategory": "应急疏散", "lab_type": "通用", "risk_level": "4",
        "hazard_types": "火灾;疏散", "scenario": "火灾应急疏散",
        "question": "实验室发生火灾时如何正确疏散？",
        "answer": "发现火情后立即停止实验，切断电源和气源，组织人员疏散。按照预先熟知的疏散路线（走道、疏散门、安全出口）迅速撤离，不得乘坐电梯。疏散时低姿前行，用湿布捂口鼻减少烟雾吸入。禁止返回烟雾区取财物。撤离后在集合点清点人员，拨打119并报告楼层、起火部位、火势大小。引导消防车进入，不得堵塞消防通道。灭火后实验室须经检查确认安全后方可重新进入。",
        "steps": "停止实验;切断电源气源;按疏散图路线撤离;不乘电梯;低姿捂口鼻;集合点清点人员;拨打119",
        "ppe": "有条件时戴防烟面罩",
        "forbidden": "禁止乘电梯;禁止返回取物;禁止堵塞疏散通道",
        "disposal": "火灾废弃物须由专业机构处理",
        "first_aid": "吸入浓烟立即转移至空气新鲜处；烧伤立即用凉水冲洗",
        "emergency": "立即拨打119；保持疏散通道畅通；安全出口不得上锁",
        "legal_notes": "遵守《高等学校实验室消防安全管理规范》JY/T 0616—2023；疏散通道不得堵塞",
        "references": "教育部《高等学校实验室消防安全管理规范》JY/T 0616—2023",
        "source_type": "应急预案", "source_title": "实验室消防应急疏散预案",
        "source_org": "教育部", "source_version": "JY/T 0616—2023",
        "source_date": "2023-06-26",
        "source_url": "https://sysglc.ntu.edu.cn/2024/0326/c8767a230277/page.htm",
        "last_updated": "2026-03-15", "reviewer": "", "status": "draft",
        "tags": "疏散;逃生;消防;应急", "language": "zh-CN",
    },
    {
        "id": "KB-1034", "title": "生物安全-生物安全柜操作规范", "category": "生物",
        "subcategory": "生物安全柜", "lab_type": "生物", "risk_level": "4",
        "hazard_types": "生物污染;气溶胶", "scenario": "生物安全柜内操作感染性材料",
        "question": "生物安全柜如何正确使用？",
        "answer": "生物安全柜是防止气溶胶暴露的核心防护设备，使用前须提前开机运行至少15分钟，等待内部气流稳定。操作时前臂缓慢移入，避免破坏气流屏障。柜内物品从清洁区到污染区依次摆放，减少交叉污染。操作感染性材料时穿戴手套、口罩、护目镜和实验服，禁止在柜外进行高风险操作。结束后用70%乙醇擦拭台面，关闭前窗，紫外灯照射仅作为补充消毒措施，不替代其他消毒手段。定期请专业机构检测性能。",
        "steps": "提前开机15分钟;检查气流指示;按清洁到污染顺序摆放;操作中不急速进出;结束后乙醇消毒台面;紫外补充消毒",
        "ppe": "双层手套;口罩或N95;护目镜;实验服",
        "forbidden": "禁止在柜外操作感染性材料;禁止在柜内使用酒精灯明火;禁止用紫外灯代替常规消毒",
        "disposal": "污染材料按生物危废处理",
        "first_aid": "皮肤暴露立即脱除手套清洗，报告并就医",
        "emergency": "气溶胶意外释放立即关闭前窗，疏散人员，通知生物安全负责人",
        "legal_notes": "遵守《病原微生物实验室生物安全管理条例》",
        "references": "实验室生物安全管理制度;高校生物安全SOP",
        "source_type": "SOP", "source_title": "生物安全柜操作规程",
        "source_org": "高校通用/教育部", "source_version": "2021",
        "source_date": "2021-01-01",
        "source_url": "https://life.sjtu.edu.cn/Data/View/6077",
        "last_updated": "2026-03-15", "reviewer": "", "status": "draft",
        "tags": "生物安全柜;气溶胶;生物安全;BSL", "language": "zh-CN",
    },
    {
        "id": "KB-1035", "title": "管理-实验室安全分级分类", "category": "通用",
        "subcategory": "安全管理", "lab_type": "通用", "risk_level": "2",
        "hazard_types": "管理;综合", "scenario": "了解实验室安全分级分类制度",
        "question": "高校实验室是如何进行安全分级分类管理的？",
        "answer": "根据教育部2024年发布的《高等学校实验室安全分级分类管理办法（试行）》，实验室按危险源类别分为：化学类、生物类、辐射类、机电类、其他类。安全等级分为四级：I级（红）重大风险、II级（橙）高风险、III级（黄）中风险、IV级（蓝）低风险。各实验室门外须设安全信息牌，标明安全类别、等级及主要危险源。高风险实验室须安装监控和报警装置，并配备足够的个体防护设备。",
        "steps": "按危险源类别判定分类;评估风险等级;设置安全信息牌;安装相应防护设施;落实对应管理措施",
        "ppe": "根据分级配备相应PPE",
        "forbidden": "禁止降低风险等级标准；禁止不设安全信息牌",
        "disposal": "",
        "first_aid": "",
        "emergency": "高风险实验室须制定对应应急预案",
        "legal_notes": "依据教育部《高等学校实验室安全分级分类管理办法（试行）》（2024年）",
        "references": "教育部《高等学校实验室安全分级分类管理办法（试行）》2024年4月",
        "source_type": "制度", "source_title": "高等学校实验室安全分级分类管理办法（试行）",
        "source_org": "教育部", "source_version": "2024",
        "source_date": "2024-04-22",
        "source_url": "https://www.edu.cn/ke_yan_yu_fa_zhan/gai_kuang/xin_wen_gong_gao/202404/t20240422_2600021.shtml",
        "last_updated": "2026-03-15", "reviewer": "", "status": "draft",
        "tags": "分级;分类;管理;教育部;红橙黄蓝", "language": "zh-CN",
    },
    {
        "id": "KB-1036", "title": "危化品-实验室储存量上限规定", "category": "化学",
        "subcategory": "储存规范", "lab_type": "化学", "risk_level": "4",
        "hazard_types": "危化品;易燃;储存", "scenario": "危化品在实验室内的储存量控制",
        "question": "实验室内危化品储存量有上限要求吗？",
        "answer": "有严格限制。根据中山大学等高校规定，实验室（除专用储存间外）其余区域暂存危化品总量：液体不超过0.2L每平方米，固体不超过0.2kg每平方米。实验台试剂架仅放当天用量，用完后放回安全柜或试剂柜。气体存储须严格分类：易燃气体不得与助燃气体或剧毒气体同存；氧气不得与油脂混合存放；易燃液体不得与氧化剂混放；氧化剂须单独存放。危化品须存放于专用安全柜，贴有完整标签。",
        "steps": "评估当日用量;当日未用完的放回安全柜;气体按类别分区存放;定期盘点并记录",
        "ppe": "护目镜;实验服;手套",
        "forbidden": "禁止超量储存;禁止易燃气体与助燃气体同存;禁止无标签存放",
        "disposal": "过期或废弃危化品按危废分类处置",
        "first_aid": "泄漏暴露按对应MSDS急救措施处理",
        "emergency": "大量泄漏按化学品泄漏应急预案处理",
        "legal_notes": "遵守《危险化学品安全管理条例》",
        "references": "中山大学实验室化学品安全管理实施细则;高等学校实验室安全规范",
        "source_type": "制度", "source_title": "实验室化学品安全管理实施细则",
        "source_org": "中山大学设备与实验室管理处", "source_version": "2023",
        "source_date": "2023-01-01",
        "source_url": "https://sbc.sysu.edu.cn/article/670",
        "last_updated": "2026-03-15", "reviewer": "", "status": "draft",
        "tags": "危化品;储存量;易燃;安全柜", "language": "zh-CN",
    },
    {
        "id": "KB-1037", "title": "应急-眼部化学灼伤处置", "category": "化学",
        "subcategory": "灼伤应急", "lab_type": "化学", "risk_level": "4",
        "hazard_types": "腐蚀性;化学灼伤", "scenario": "化学品溅入眼睛的急救处置",
        "question": "化学品溅入眼睛怎么紧急处理？",
        "answer": "化学品溅入眼睛是高优先级紧急情况，必须立即处置。第一步：用大量清水持续冲洗眼睛至少15分钟，冲洗时用手指撑开眼睑，使水流能冲洗眼球各部位；如实验室有洗眼器应立即使用。第二步：冲洗的同时呼叫他人协助，摘除隐形眼镜（若有）。第三步：冲洗后立即就医，并告知医生所接触的化学品种类。禁止揉眼睛，禁止用有色液体中和冲洗。酸、碱或有机溶剂溅入处置原则相同，均以大量清水冲洗为优先。",
        "steps": "立即用清水冲洗眼睛15分钟以上;撑开眼睑充分冲洗;摘除隐形眼镜;呼叫他人协助;告知化学品种类后立即就医",
        "ppe": "操作化学品时佩戴护目镜可预防此类事故",
        "forbidden": "禁止揉搓眼睛;禁止用有色液体冲洗;禁止延误就医",
        "disposal": "",
        "first_aid": "洗眼器冲洗至少15分钟，立即就医",
        "emergency": "立即启用洗眼器，呼叫他人协助并拨打急救电话",
        "legal_notes": "实验室应配备可用洗眼器，定期检查有效性",
        "references": "高校实验室化学灼伤急救标准操作;GBZ/T 256消毒冲洗规范",
        "source_type": "应急预案", "source_title": "化学灼伤（眼部）急救规程",
        "source_org": "高校通用/教育部", "source_version": "2023",
        "source_date": "2023-01-01",
        "source_url": "https://sbc.sysu.edu.cn/article/570",
        "last_updated": "2026-03-15", "reviewer": "", "status": "draft",
        "tags": "眼部灼伤;化学灼伤;洗眼器;急救", "language": "zh-CN",
    },
]

csv_path = Path("knowledge_base_curated.csv")
with csv_path.open("r", encoding="utf-8-sig", newline="") as f:
    rows = list(csv.DictReader(f))

existing_ids = {r["id"] for r in rows}
added = 0
for entry in new_entries:
    if entry["id"] not in existing_ids:
        rows.append({field: entry.get(field, "") for field in KB_FIELDNAMES})
        existing_ids.add(entry["id"])
        added += 1

with csv_path.open("w", encoding="utf-8-sig", newline="") as f:
    writer = csv.DictWriter(f, fieldnames=KB_FIELDNAMES)
    writer.writeheader()
    for row in rows:
        writer.writerow(row)

print(f"Added {added} new hand-curated entries. Total rows: {len(rows)}")
