#!/usr/bin/env python3
"""
Knowledge Base Scene Expansion Script

This script adds new KB entries to cover additional lab safety scenarios:
- Electrophoresis (EB gel)
- PCR 
- Cell culture
- Radioactive experiments
"""

import csv
from datetime import datetime
from pathlib import Path


NEW_KB_ENTRIES = [
    {
        "id": "KB-1044",
        "title": "电泳安全-琼脂糖凝胶制备",
        "category": "化学",
        "subcategory": "电泳安全",
        "lab_type": "生物",
        "risk_level": "3",
        "hazard_types": "化学接触;烫伤",
        "scenario": "配制琼脂糖凝胶用于 DNA 电泳",
        "question": "配制琼脂糖凝胶时需要注意哪些安全事项？",
        "answer": "配制琼脂糖凝胶时需要注意：使用手套避免直接接触核酸染料（如 EB）；琼脂糖粉应在通风柜内称量；加热琼脂糖溶液时需戴防烫手套，使用微波炉或电炉时防止暴沸；倒入凝胶模具前需冷却至60度以下。",
        "steps": "称量琼脂糖;加缓冲液;加热溶解;冷却至60度;倒入模具",
        "ppe": "手套;护目镜;实验服",
        "forbidden": "禁止徒手接触 EB;禁止在微波炉中加热过度",
        "disposal": "含 EB 的凝胶按有害垃圾处理",
        "first_aid": "皮肤接触立即用清水冲洗",
        "emergency": "烫伤按烧伤处理",
        "legal_notes": "遵守实验室废弃物分类规定",
        "references": "",
        "source_type": "SOP",
        "source_title": "电泳实验安全操作规范",
        "source_org": "实验室管理处",
        "source_version": "v1.0",
        "source_date": "2026-03-20",
        "source_url": "内部管理制度（待获取正式URL）",
        "last_updated": "2026-03-20",
        "reviewer": "系统管理员",
        "status": "active",
        "tags": "电泳;凝胶;EB;核酸",
        "language": "zh-CN"
    },
    {
        "id": "KB-1045",
        "title": "电泳安全-电泳槽操作",
        "category": "化学",
        "subcategory": "电泳安全",
        "lab_type": "生物",
        "risk_level": "4",
        "hazard_types": "触电;化学",
        "scenario": "使用电泳槽进行 DNA 电泳",
        "question": "使用电泳槽时有哪些安全注意事项？",
        "answer": "使用电泳槽时应注意：确保电极连接正确，无裸露导线；加样前先打开电源确认无短路；运行时禁止触碰电极和缓冲液；电泳结束后先关闭电源再开盖取胶；如有液体漏出立即断电处理。",
        "steps": "检查电极;加缓冲液;加样;设置参数;启动电泳;结束处理",
        "ppe": "手套;护目镜",
        "forbidden": "禁止带电操作;禁止触碰电极",
        "disposal": "用完的凝胶按生物有害垃圾处理",
        "first_aid": "触电立即断电并按应急预案处理",
        "emergency": "触电按电气事故应急预案处理",
        "legal_notes": "遵守电气安全操作规程",
        "references": "",
        "source_type": "SOP",
        "source_title": "电泳实验安全操作规范",
        "source_org": "实验室管理处",
        "source_version": "v1.0",
        "source_date": "2026-03-20",
        "source_url": "内部管理制度（待获取正式URL）",
        "last_updated": "2026-03-20",
        "reviewer": "系统管理员",
        "status": "active",
        "tags": "电泳;电泳槽;触电",
        "language": "zh-CN"
    },
    {
        "id": "KB-1046",
        "title": "PCR 实验安全-试剂配制",
        "category": "生物",
        "subcategory": "分子生物学",
        "lab_type": "生物",
        "risk_level": "2",
        "hazard_types": "生物污染",
        "scenario": "配制 PCR 反应体系",
        "question": "配制 PCR 反应体系时需要注意什么？",
        "answer": "配制 PCR 反应体系时需注意：在超净台或干净区域操作；使用专用移液器和枪头，避免交叉污染；Taq 酶和 DNA 模板最后加入；反应管标注清晰；操作完成后及时冰浴保存。",
        "steps": "准备试剂;配制混合液;加模板;标记保存",
        "ppe": "手套;实验服",
        "forbidden": "禁止交叉污染;禁止用嘴吸液",
        "disposal": "废弃 tip 头和反应管按生物废液处理",
        "first_aid": "如有试剂溅入眼睛立即用清水冲洗",
        "emergency": "按生物安全应急预案处理",
        "legal_notes": "遵守分子生物学实验规范",
        "references": "",
        "source_type": "SOP",
        "source_title": "PCR 实验操作规范",
        "source_org": "实验室管理处",
        "source_version": "v1.0",
        "source_date": "2026-03-20",
        "source_url": "内部管理制度（待获取正式URL）",
        "last_updated": "2026-03-20",
        "reviewer": "系统管理员",
        "status": "active",
        "tags": "PCR;分子生物学;核酸",
        "language": "zh-CN"
    },
    {
        "id": "KB-1047",
        "title": "PCR 实验安全-扩增产物处理",
        "category": "生物",
        "subcategory": "分子生物学",
        "lab_type": "生物",
        "risk_level": "3",
        "hazard_types": "生物污染",
        "scenario": "处理 PCR 扩增产物（凝胶电泳）",
        "question": "处理 PCR 扩增产物时有哪些安全注意事项？",
        "answer": "处理 PCR 扩增产物时需注意：产物视为含有生物材料，操作时佩戴手套；在指定区域进行电泳；切胶时佩戴手套和口罩，避免接触 EB 等染料；产物回收后妥善保存或销毁。",
        "steps": "配制凝胶;加样电泳;凝胶成像;切胶回收",
        "ppe": "手套;口罩;护目镜",
        "forbidden": "禁止徒手接触凝胶;禁止在开放区域操作",
        "disposal": "含 EB 凝胶和废弃产物按生物有害垃圾处理",
        "first_aid": "EB 接触皮肤用清水冲洗",
        "emergency": "按生物安全应急预案处理",
        "legal_notes": "遵守废弃物分类规定",
        "references": "",
        "source_type": "SOP",
        "source_title": "PCR 实验操作规范",
        "source_org": "实验室管理处",
        "source_version": "v1.0",
        "source_date": "2026-03-20",
        "source_url": "内部管理制度（待获取正式URL）",
        "last_updated": "2026-03-20",
        "reviewer": "系统管理员",
        "status": "active",
        "tags": "PCR;电泳;EB;凝胶回收",
        "language": "zh-CN"
    },
    {
        "id": "KB-1048",
        "title": "细胞培养安全-无菌操作",
        "category": "生物",
        "subcategory": "细胞培养",
        "lab_type": "生物",
        "risk_level": "4",
        "hazard_types": "生物污染;感染",
        "scenario": "在细胞培养室进行无菌操作",
        "question": "细胞培养的无菌操作有哪些要点？",
        "answer": "细胞培养无菌操作要点：进入培养室前更换专用实验服、鞋套；操作前用酒精擦拭手套；所有试剂和器具需灭菌处理；在生物安全柜内操作；减少在安全柜内过多动作；定期检测支原体污染。",
        "steps": "更衣换鞋;手部消毒;生物安全柜操作;定期检测",
        "ppe": "实验服;鞋套;手套;口罩",
        "forbidden": "禁止不更衣进入培养室;禁止在开放环境操作",
        "disposal": "污染的耗材按生物有害垃圾处理",
        "first_aid": "培养物溅出立即消毒处理",
        "emergency": "按生物安全应急预案处理",
        "legal_notes": "遵守细胞培养实验室管理规定",
        "references": "",
        "source_type": "SOP",
        "source_title": "细胞培养室管理规范",
        "source_org": "实验室管理处",
        "source_version": "v1.0",
        "source_date": "2026-03-20",
        "source_url": "内部管理制度（待获取正式URL）",
        "last_updated": "2026-03-20",
        "reviewer": "系统管理员",
        "status": "active",
        "tags": "细胞培养;无菌操作;生物安全柜",
        "language": "zh-CN"
    },
    {
        "id": "KB-1049",
        "title": "细胞培养安全-支原体污染",
        "category": "生物",
        "subcategory": "细胞培养",
        "lab_type": "生物",
        "risk_level": "3",
        "hazard_types": "生物污染",
        "scenario": "发现细胞培养物疑似支原体污染",
        "question": "发现细胞培养疑似支原体污染应该怎么处理？",
        "answer": "发现支原体污染时应：立即停止使用该批细胞；标记受污染的培养箱区域；对培养箱进行全面消毒；检查其他细胞是否受影响；必要时弃用所有可疑细胞并重新复苏；上报实验室负责人。",
        "steps": "停止使用;标记污染区;消毒培养箱;检测其他细胞;上报",
        "ppe": "手套;口罩;实验服",
        "forbidden": "禁止继续使用污染细胞;禁止在不通风区域处理",
        "disposal": "污染细胞和培养基按生物有害垃圾处理",
        "first_aid": "如有培养物溅入口腔立即漱口并就医",
        "emergency": "按生物安全应急预案处理并就医",
        "legal_notes": "遵守实验室生物安全管理规定",
        "references": "",
        "source_type": "SOP",
        "source_title": "细胞培养室管理规范",
        "source_org": "实验室管理处",
        "source_version": "v1.0",
        "source_date": "2026-03-20",
        "source_url": "内部管理制度（待获取正式URL）",
        "last_updated": "2026-03-20",
        "reviewer": "系统管理员",
        "status": "active",
        "tags": "细胞培养;支原体;污染",
        "language": "zh-CN"
    },
    {
        "id": "KB-1050",
        "title": "放射性实验-碘-125 操作",
        "category": "辐射",
        "subcategory": "放射性实验",
        "lab_type": "辐射",
        "risk_level": "5",
        "hazard_types": "辐射污染;放射性",
        "scenario": "使用碘-125 进行放射性标记实验",
        "question": "操作碘-125 有哪些特殊安全要求？",
        "answer": "操作碘-125 必须：持有辐射安全培训合格证；在专用放射性操作柜中进行；穿戴铅衣、铅围脖、手套等防护用品；使用长柄工具减少近距离接触；操作台铺有吸附垫；实验结束后进行表面污染监测。",
        "steps": "确认资质;穿戴防护;准备操作柜;进行标记;污染监测;废物处置",
        "ppe": "铅衣;铅围脖;铅玻璃眼镜;手套;鞋套",
        "forbidden": "禁止无证操作;禁止徒手直接接触",
        "disposal": "放射性废物按辐射废物管理规定处置",
        "first_aid": "污染伤口立即冲洗并就医",
        "emergency": "辐射事故按应急预案处理并报告",
        "legal_notes": "遵守辐射防护规定和许可证要求",
        "references": "",
        "source_type": "SOP",
        "source_title": "放射性同位素实验安全规范",
        "source_org": "辐射安全管理委员会",
        "source_version": "v1.0",
        "source_date": "2026-03-20",
        "source_url": "内部管理制度（待获取正式URL）",
        "last_updated": "2026-03-20",
        "reviewer": "系统管理员",
        "status": "active",
        "tags": "放射性;碘-125;辐射防护",
        "language": "zh-CN"
    },
    {
        "id": "KB-1051",
        "title": "放射性实验-碳-14 操作",
        "category": "辐射",
        "subcategory": "放射性实验",
        "lab_type": "辐射",
        "risk_level": "4",
        "hazard_types": "辐射污染;放射性",
        "scenario": "使用碳-14 进行放射性标记实验",
        "question": "操作碳-14 有哪些安全注意事项？",
        "answer": "操作碳-14 应注意：在通风柜内操作；佩戴个人剂量计和防护手套；避免摄入含碳-14 的气体或液体；操作台铺防护垫；废物分类收集；定期进行污染监测。",
        "steps": "确认资质;穿戴防护;通风柜操作;污染监测;废物处置",
        "ppe": "实验服;手套;口罩;个人剂量计",
        "forbidden": "禁止在开放环境操作;禁止摄入",
        "disposal": "含碳-14 废物按放射性废物处置",
        "first_aid": "污染立即用大量清水冲洗",
        "emergency": "辐射事故按应急预案处理",
        "legal_notes": "遵守辐射防护规定",
        "references": "",
        "source_type": "SOP",
        "source_title": "放射性同位素实验安全规范",
        "source_org": "辐射安全管理委员会",
        "source_version": "v1.0",
        "source_date": "2026-03-20",
        "source_url": "内部管理制度（待获取正式URL）",
        "last_updated": "2026-03-20",
        "reviewer": "系统管理员",
        "status": "active",
        "tags": "放射性;碳-14;辐射防护",
        "language": "zh-CN"
    },
    {
        "id": "KB-1052",
        "title": "放射性实验-表面污染监测",
        "category": "辐射",
        "subcategory": "放射性实验",
        "lab_type": "辐射",
        "risk_level": "3",
        "hazard_types": "辐射污染",
        "scenario": "放射性实验结束后的表面污染监测",
        "question": "放射性实验结束后如何进行表面污染监测？",
        "answer": "放射性实验结束后应：使用表面污染仪对操作区域进行系统性扫描；重点监测操作台、设备表面、手套、实验服等；记录监测结果并存档；如发现污染立即标记并去污处理。",
        "steps": "准备监测仪器;系统性扫描;记录结果;去污处理;确认合格",
        "ppe": "手套;实验服",
        "forbidden": "禁止跳过监测步骤",
        "disposal": "污染擦拭物按放射性废物处理",
        "first_aid": "监测过程中发现异常立即报告",
        "emergency": "超标污染按辐射事故应急预案处理",
        "legal_notes": "遵守辐射环境监测规定",
        "references": "",
        "source_type": "SOP",
        "source_title": "放射性实验环境监测规范",
        "source_org": "辐射安全管理委员会",
        "source_version": "v1.0",
        "source_date": "2026-03-20",
        "source_url": "内部管理制度（待获取正式URL）",
        "last_updated": "2026-03-20",
        "reviewer": "系统管理员",
        "status": "active",
        "tags": "放射性;污染监测;辐射安全",
        "language": "zh-CN"
    },
    {
        "id": "KB-1053",
        "title": "离心机安全-转头选择",
        "category": "通用",
        "subcategory": "离心机安全",
        "lab_type": "通用",
        "risk_level": "3",
        "hazard_types": "机械伤害",
        "scenario": "选择离心机转头和离心管",
        "question": "选择离心机转头和离心管时需要注意什么？",
        "answer": "选择转头和离心管时应注意：转头型号须与离心机匹配；离心管容量不得超过转头最大承载；使用相同规格、相同重量的离心管对称放置；检查管壁有无裂纹；确保密封良好。",
        "steps": "确认转头型号;选择匹配离心管;对称放置;检查密封",
        "ppe": "手套;实验服",
        "forbidden": "禁止超载使用;禁止使用破损离心管",
        "disposal": "破损离心管按实验室废弃物处理",
        "first_aid": "离心过程异常立即停机检查",
        "emergency": "异常震动立即停机并报告",
        "legal_notes": "遵守离心机操作规程",
        "references": "",
        "source_type": "SOP",
        "source_title": "离心机安全操作规范",
        "source_org": "实验室管理处",
        "source_version": "v1.0",
        "source_date": "2026-03-20",
        "source_url": "内部管理制度（待获取正式URL）",
        "last_updated": "2026-03-20",
        "reviewer": "系统管理员",
        "status": "active",
        "tags": "离心机;转头;平衡",
        "language": "zh-CN"
    },
    {
        "id": "KB-1054",
        "title": "高压灭菌锅安全-物品装载",
        "category": "通用",
        "subcategory": "高压灭菌锅",
        "lab_type": "通用",
        "risk_level": "3",
        "hazard_types": "高温;高压",
        "scenario": "高压灭菌锅的物品装载",
        "question": "使用高压灭菌锅时物品装载有哪些要求？",
        "answer": "高压灭菌锅装载时应注意：物品不要装得过满，保持蒸汽流通空间；液体灭菌使用专用容器，盖子松开；包裹物品不要太紧；大型物品使用专用架子；灭菌物品晾干后再取出。",
        "steps": "分类装载;松盖液体;保持间距;设置参数;冷却后取出",
        "ppe": "防烫手套;实验服",
        "forbidden": "禁止超载;禁止液体灭菌盖紧盖子",
        "disposal": "灭菌后物品按无菌物品管理",
        "first_aid": "烫伤立即用冷水冲洗并就医",
        "emergency": "压力异常立即停机并报告",
        "legal_notes": "遵守高压灭菌锅操作规程",
        "references": "",
        "source_type": "SOP",
        "source_title": "高压灭菌锅安全操作规范",
        "source_org": "实验室管理处",
        "source_version": "v1.0",
        "source_date": "2026-03-20",
        "source_url": "内部管理制度（待获取正式URL）",
        "last_updated": "2026-03-20",
        "reviewer": "系统管理员",
        "status": "active",
        "tags": "高压灭菌锅;灭菌;装载",
        "language": "zh-CN"
    }
]


KB_FIELDNAMES = [
    "id", "title", "category", "subcategory", "lab_type", "risk_level",
    "hazard_types", "scenario", "question", "answer", "steps", "ppe",
    "forbidden", "disposal", "first_aid", "emergency", "legal_notes",
    "references", "source_type", "source_title", "source_org",
    "source_version", "source_date", "source_url", "last_updated",
    "reviewer", "status", "tags", "language"
]


def main() -> int:
    kb_path = Path("knowledge_base_curated.csv")

    with kb_path.open("r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        existing_ids = {row["id"] for row in reader}

    new_entries = [e for e in NEW_KB_ENTRIES if e["id"] not in existing_ids]

    if not new_entries:
        print("所有新条目已存在，无需添加")
        return 0

    with kb_path.open("a", encoding="utf-8-sig", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=KB_FIELDNAMES)
        writer.writerows(new_entries)

    print(f"已添加 {len(new_entries)} 条新 KB 条目")
    print(f"KB 总条目数: {len(existing_ids) + len(new_entries)}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
