#!/usr/bin/env python3
"""
Generate weekly gate operations report from GitHub alert issues.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import urllib.parse
import urllib.request
from dataclasses import dataclass
from datetime import date, datetime, timedelta, timezone
from pathlib import Path
from typing import Any


TITLE_DATE_PATTERN = re.compile(r"^\[Eval Gate\] (\d{4}-\d{2}-\d{2}) gate failed$")


@dataclass
class Issue:
    number: int
    title: str
    state: str
    created_at: datetime
    updated_at: datetime
    closed_at: datetime | None
    labels: set[str]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate weekly gate ops markdown report.")
    parser.add_argument("--repo-root", default=".", help="Repository root.")
    parser.add_argument(
        "--output",
        default="docs/eval/weekly_gate_ops.md",
        help="Output markdown path.",
    )
    parser.add_argument(
        "--days",
        type=int,
        default=7,
        help="Rolling day window for summary.",
    )
    parser.add_argument(
        "--repo",
        default=os.environ.get("GITHUB_REPOSITORY", ""),
        help="GitHub repository in owner/name format.",
    )
    parser.add_argument(
        "--token",
        default=os.environ.get("GITHUB_TOKEN", ""),
        help="GitHub token. If empty, use --issues-json.",
    )
    parser.add_argument(
        "--issues-json",
        default="",
        help="Optional local issues json for offline generation/testing.",
    )
    parser.add_argument(
        "--release-fix-issues-json",
        default="",
        help="Optional local release-fix issues json for offline generation/testing.",
    )
    parser.add_argument(
        "--today",
        default="",
        help="Optional override date in YYYY-MM-DD (for testing).",
    )
    parser.add_argument(
        "--failover-status-json",
        default="docs/eval/failover_status.json",
        help="Optional failover status json generated by generate_failover_status.py",
    )
    return parser.parse_args()


def parse_dt(value: str) -> datetime:
    raw = (value or "").strip()
    if raw.endswith("Z"):
        raw = raw[:-1] + "+00:00"
    return datetime.fromisoformat(raw).astimezone(timezone.utc)


def parse_issue(item: dict[str, Any]) -> Issue | None:
    if "pull_request" in item:
        return None
    labels_raw = item.get("labels", [])
    labels: set[str] = set()
    if isinstance(labels_raw, list):
        for label in labels_raw:
            if isinstance(label, dict):
                name = str(label.get("name", "")).strip()
                if name:
                    labels.add(name)
            elif isinstance(label, str):
                name = label.strip()
                if name:
                    labels.add(name)
    try:
        number = int(item.get("number", 0) or 0)
        title = str(item.get("title", "") or "").strip()
        state = str(item.get("state", "") or "").strip().lower()
        created_at = parse_dt(str(item.get("created_at", "") or ""))
        updated_at = parse_dt(str(item.get("updated_at", "") or ""))
        closed_raw = str(item.get("closed_at", "") or "").strip()
        closed_at = parse_dt(closed_raw) if closed_raw else None
    except Exception:
        return None
    if number <= 0 or not title:
        return None
    return Issue(
        number=number,
        title=title,
        state=state,
        created_at=created_at,
        updated_at=updated_at,
        closed_at=closed_at,
        labels=labels,
    )


def github_get_json(url: str, token: str) -> Any:
    req = urllib.request.Request(
        url,
        headers={
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
            "User-Agent": "lab-safe-assistant-weekly-gate-ops",
        },
        method="GET",
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        body = resp.read().decode("utf-8", errors="ignore")
    return json.loads(body)


def load_issues_from_github_by_label(repo: str, token: str, *, labels: str) -> list[Issue]:
    owner, name = repo.split("/", 1)
    all_issues: list[Issue] = []
    per_page = 100
    for page in range(1, 11):
        qs = urllib.parse.urlencode(
            {
                "state": "all",
                "labels": labels,
                "per_page": per_page,
                "page": page,
            }
        )
        url = f"https://api.github.com/repos/{owner}/{name}/issues?{qs}"
        payload = github_get_json(url, token=token)
        if not isinstance(payload, list):
            break
        page_items = 0
        for raw in payload:
            if isinstance(raw, dict):
                issue = parse_issue(raw)
                if issue is not None:
                    all_issues.append(issue)
                    page_items += 1
        if page_items < per_page:
            break
    return all_issues


def load_issues_from_json(path: Path) -> list[Issue]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, list):
        raise ValueError("issues-json must be a JSON array")
    issues: list[Issue] = []
    for raw in payload:
        if isinstance(raw, dict):
            issue = parse_issue(raw)
            if issue is not None:
                issues.append(issue)
    return issues


def title_date(title: str) -> date | None:
    match = TITLE_DATE_PATTERN.match(title.strip())
    if not match:
        return None
    try:
        return date.fromisoformat(match.group(1))
    except ValueError:
        return None


def summarize(issues: list[Issue], *, start: date, end: date) -> dict[str, Any]:
    gate_issues = [
        issue for issue in issues if ("eval-gate-alert" in issue.labels or title_date(issue.title) is not None)
    ]
    day_total = (end - start).days + 1
    by_day: dict[str, Issue] = {}
    for issue in gate_issues:
        d = title_date(issue.title)
        if d is None or d < start or d > end:
            continue
        key = d.isoformat()
        prev = by_day.get(key)
        if prev is None or issue.updated_at > prev.updated_at:
            by_day[key] = issue

    fail_days = len(by_day)
    pass_days = max(0, day_total - fail_days)
    p1_days = sum(1 for issue in by_day.values() if "p1-gate" in issue.labels)
    open_alerts = sum(1 for issue in gate_issues if issue.state == "open")
    open_p1 = sum(1 for issue in gate_issues if issue.state == "open" and "p1-gate" in issue.labels)
    open_sla_missing = sum(
        1 for issue in gate_issues if issue.state == "open" and "sla-missing" in issue.labels
    )

    rows = []
    current = start
    while current <= end:
        key = current.isoformat()
        issue = by_day.get(key)
        if issue is None:
            rows.append(
                {
                    "date": key,
                    "result": "PASS",
                    "issue_number": "",
                    "labels": "",
                }
            )
        else:
            labels = sorted(issue.labels)
            rows.append(
                {
                    "date": key,
                    "result": "FAIL",
                    "issue_number": f"#{issue.number}",
                    "labels": ",".join(labels),
                }
            )
        current += timedelta(days=1)

    return {
        "start": start.isoformat(),
        "end": end.isoformat(),
        "days": day_total,
        "fail_days": fail_days,
        "pass_days": pass_days,
        "p1_days": p1_days,
        "open_alerts": open_alerts,
        "open_p1": open_p1,
        "open_sla_missing": open_sla_missing,
        "rows": rows,
    }


def summarize_release_fix_p0(issues: list[Issue], *, start: date, end: date) -> dict[str, Any]:
    filtered = [
        issue
        for issue in issues
        if "release-fix-task" in issue.labels and "priority-p0" in issue.labels
    ]
    created_in_window = sum(1 for issue in filtered if start <= issue.created_at.date() <= end)
    closed_in_window = sum(
        1
        for issue in filtered
        if issue.closed_at is not None and start <= issue.closed_at.date() <= end
    )
    open_now = [issue for issue in filtered if issue.state == "open"]
    stale_open_7d = sum(1 for issue in open_now if (end - issue.created_at.date()).days >= 7)
    open_rows = sorted(
        [
            {
                "number": issue.number,
                "title": issue.title,
                "created_at": issue.created_at.date().isoformat(),
                "updated_at": issue.updated_at.date().isoformat(),
                "labels": ",".join(sorted(issue.labels)),
            }
            for issue in open_now
        ],
        key=lambda item: item["number"],
    )
    return {
        "total_p0": len(filtered),
        "created_in_window": created_in_window,
        "closed_in_window": closed_in_window,
        "open_now": len(open_now),
        "stale_open_7d": stale_open_7d,
        "open_rows": open_rows,
    }


def load_failover_status(path: Path) -> dict[str, Any] | None:
    if not path.exists():
        return None
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return None
    if not isinstance(payload, dict):
        return None
    return payload


def render_markdown(
    summary: dict[str, Any],
    *,
    generated_at: str,
    source: str,
    release_fix_summary: dict[str, Any] | None = None,
    release_fix_source: str = "",
    failover_status: dict[str, Any] | None = None,
) -> str:
    lines: list[str] = []
    lines.append("# Weekly Gate Ops")
    lines.append("")
    lines.append(f"- Generated At: `{generated_at}`")
    lines.append(f"- Window: `{summary['start']}` to `{summary['end']}`")
    lines.append(f"- Source: `{source}`")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("|---|---:|")
    lines.append(f"| Window Days | {summary['days']} |")
    lines.append(f"| PASS Days | {summary['pass_days']} |")
    lines.append(f"| FAIL Days | {summary['fail_days']} |")
    lines.append(f"| P1 Days | {summary['p1_days']} |")
    lines.append(f"| Open Alerts | {summary['open_alerts']} |")
    lines.append(f"| Open P1 Alerts | {summary['open_p1']} |")
    lines.append(f"| Open SLA Missing | {summary['open_sla_missing']} |")
    lines.append("")
    lines.append("## Daily Breakdown")
    lines.append("")
    lines.append("| Date | Gate Result | Issue | Labels |")
    lines.append("|---|---|---|---|")
    for row in summary["rows"]:
        lines.append(
            f"| {row['date']} | {row['result']} | {row['issue_number']} | {row['labels']} |"
        )
    lines.append("")
    lines.append("## Notes")
    lines.append("")
    lines.append("- `FAIL` is inferred from `eval-gate-alert` issue existence for that date.")
    lines.append("- `PASS` is inferred when no `eval-gate-alert` issue exists for that date in the window.")
    if release_fix_summary is not None:
        lines.append("")
        lines.append("## Release Fix P0 Summary")
        lines.append("")
        if release_fix_source:
            lines.append(f"- Source: `{release_fix_source}`")
            lines.append("")
        lines.append("| Metric | Value |")
        lines.append("|---|---:|")
        lines.append(f"| Total P0 Tasks (all-time issues) | {release_fix_summary['total_p0']} |")
        lines.append(f"| Created in Window | {release_fix_summary['created_in_window']} |")
        lines.append(f"| Closed in Window | {release_fix_summary['closed_in_window']} |")
        lines.append(f"| Open Now | {release_fix_summary['open_now']} |")
        lines.append(f"| Open >= 7 Days | {release_fix_summary['stale_open_7d']} |")
        lines.append("")
        lines.append("### Open P0 Tasks")
        lines.append("")
        lines.append("| Issue | Title | Created | Updated | Labels |")
        lines.append("|---|---|---|---|---|")
        if release_fix_summary["open_rows"]:
            for row in release_fix_summary["open_rows"]:
                title = str(row["title"]).replace("|", "\\|")
                lines.append(
                    f"| #{row['number']} | {title} | {row['created_at']} | {row['updated_at']} | {row['labels']} |"
                )
        else:
            lines.append("| - | none | - | - | - |")
    if failover_status:
        lines.append("")
        lines.append("## Failover Snapshot")
        lines.append("")
        latest = failover_status.get("latest") or {}
        counts = failover_status.get("window_counts") or {}
        lines.append("| Metric | Value |")
        lines.append("|---|---:|")
        lines.append(f"| Failover Window Days | {failover_status.get('window_days', 0)} |")
        lines.append(f"| Failover PASS | {counts.get('pass', 0)} |")
        lines.append(f"| Failover DEGRADED | {counts.get('degraded', 0)} |")
        lines.append(f"| Failover FAIL | {counts.get('fail', 0)} |")
        lines.append(f"| Failover Triggered | {counts.get('failover_triggered', 0)} |")
        lines.append("")
        if latest:
            lines.append(f"- Latest Failover Result: `{latest.get('result', 'unknown')}`")
            lines.append(f"- Latest Failover Time: `{latest.get('generated_at', '')}`")
            lines.append(f"- Latest Final Model: `{latest.get('active_model_final', '')}`")
            lines.append(f"- Latest Failover Reason: `{latest.get('failover_reason', '')}`")
        else:
            lines.append("- Latest Failover Result: `none`")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    args = parse_args()
    repo_root = Path(args.repo_root).resolve()
    output_path = Path(args.output)
    if not output_path.is_absolute():
        output_path = repo_root / output_path

    today = date.fromisoformat(args.today) if args.today else datetime.now(timezone.utc).date()
    days = max(1, int(args.days))
    start = today - timedelta(days=days - 1)

    source = ""
    release_fix_source = ""
    if args.issues_json:
        issues_path = Path(args.issues_json)
        if not issues_path.is_absolute():
            issues_path = repo_root / issues_path
        issues = load_issues_from_json(issues_path)
        source = f"issues-json:{issues_path}"
        if args.release_fix_issues_json:
            release_fix_path = Path(args.release_fix_issues_json)
            if not release_fix_path.is_absolute():
                release_fix_path = repo_root / release_fix_path
            release_fix_issues = load_issues_from_json(release_fix_path)
            release_fix_source = f"issues-json:{release_fix_path}"
        else:
            release_fix_issues = issues
            release_fix_source = source
    else:
        repo = (args.repo or "").strip()
        token = (args.token or "").strip()
        if not repo or not token:
            raise SystemExit(
                "Missing repo/token. Provide --issues-json or set GITHUB_REPOSITORY + GITHUB_TOKEN."
            )
        issues = load_issues_from_github_by_label(repo=repo, token=token, labels="eval-gate-alert")
        source = f"github:{repo}"
        release_fix_issues = load_issues_from_github_by_label(
            repo=repo,
            token=token,
            labels="release-fix-task,priority-p0",
        )
        release_fix_source = f"github:{repo}:release-fix-task+priority-p0"

    summary = summarize(issues, start=start, end=today)
    release_fix_summary = summarize_release_fix_p0(release_fix_issues, start=start, end=today)
    generated_at = datetime.now(timezone.utc).isoformat(timespec="seconds")
    failover_path = Path(args.failover_status_json)
    if not failover_path.is_absolute():
        failover_path = repo_root / failover_path
    failover_status = load_failover_status(failover_path)

    markdown = render_markdown(
        summary,
        generated_at=generated_at,
        source=source,
        release_fix_summary=release_fix_summary,
        release_fix_source=release_fix_source,
        failover_status=failover_status,
    )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(markdown, encoding="utf-8")

    print(f"Generated weekly gate ops: {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
