from __future__ import annotations

import argparse
import csv
import json
from datetime import datetime
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate and append a release review entry markdown block."
    )
    parser.add_argument("--batch-name", required=True, help="Release batch name.")
    parser.add_argument(
        "--run-report",
        required=True,
        help="Path to run_report.json generated by unified_kb_pipeline.",
    )
    parser.add_argument(
        "--manual-review",
        default="",
        help="Optional path to manual_review_sheet.csv.",
    )
    parser.add_argument("--reviewer-a", required=True, help="Reviewer A (name or GitHub ID).")
    parser.add_argument("--reviewer-b", required=True, help="Reviewer B (name or GitHub ID).")
    parser.add_argument(
        "--eval-set-version",
        default="eval_set_v1.csv",
        help="Eval set version or filename.",
    )
    parser.add_argument(
        "--human-review-questions",
        type=int,
        default=20,
        help="How many manual review questions were checked.",
    )
    parser.add_argument(
        "--human-review-pass",
        type=int,
        default=0,
        help="How many manual review questions passed.",
    )
    parser.add_argument(
        "--high-risk-errors",
        type=int,
        default=0,
        help="Count of high-risk incorrect suggestions.",
    )
    parser.add_argument(
        "--allow-release",
        choices=["yes", "no"],
        default="no",
        help="Whether this batch is approved for release.",
    )
    parser.add_argument(
        "--notes",
        default="",
        help="Additional notes.",
    )
    parser.add_argument(
        "--output",
        default="docs/release_review_log.md",
        help="Output markdown file to append entry.",
    )
    parser.add_argument(
        "--csv-output",
        default="docs/release_review_log.csv",
        help="CSV log output file for structured release review statistics.",
    )
    parser.add_argument(
        "--gate-flag",
        default="docs/release_review_gate_enabled.flag",
        help="Gate flag file path. Created/updated after first entry is appended.",
    )
    parser.add_argument(
        "--skip-gate-flag",
        action="store_true",
        help="Do not touch gate flag file.",
    )
    return parser.parse_args()


def load_run_report(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def summarize_manual_review(path: Path) -> tuple[int, int, int]:
    """
    Returns:
      total_rows, done_rows, pending_rows
    """
    total_rows = 0
    done_rows = 0
    pending_rows = 0

    with path.open("r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            total_rows += 1
            status = (row.get("manual_review_status") or "").strip().lower()
            if status == "done":
                done_rows += 1
            else:
                pending_rows += 1

    return total_rows, done_rows, pending_rows


def extract_counts(run_report: dict) -> tuple[int, int, int]:
    doc_rows = int(run_report.get("documents_rows", run_report.get("document_rows", 0)))
    web_rows = int(run_report.get("web_rows", 0))
    merged_rows = int(run_report.get("merged_rows", 0))
    return doc_rows, web_rows, merged_rows


def build_block(
    *,
    batch_name: str,
    review_date: str,
    reviewer_a: str,
    reviewer_b: str,
    eval_set_version: str,
    human_questions: int,
    human_pass: int,
    high_risk_errors: int,
    allow_release: str,
    notes: str,
    doc_rows: int,
    web_rows: int,
    merged_rows: int,
    manual_total: int | None,
    manual_done: int | None,
    manual_pending: int | None,
) -> str:
    lines: list[str] = []
    lines.append(f"## 发布批次：{batch_name}")
    lines.append("")
    lines.append(f"- 审核日期：{review_date}")
    lines.append(f"- 审核人A：{reviewer_a}")
    lines.append(f"- 审核人B：{reviewer_b}")
    lines.append(f"- 使用评测集版本：{eval_set_version}")
    lines.append(f"- 人工审核题数：{human_questions}")
    lines.append(f"- 通过题数：{human_pass}")
    lines.append(f"- 高风险错误建议（0/1+）：{high_risk_errors}")
    lines.append(f"- 结论（允许发布 yes/no）：{allow_release}")
    lines.append("- 自动统计：")
    lines.append(f"  - document_rows={doc_rows}")
    lines.append(f"  - web_rows={web_rows}")
    lines.append(f"  - merged_rows={merged_rows}")
    if manual_total is not None:
        lines.append(f"  - manual_review_total={manual_total}")
        lines.append(f"  - manual_review_done={manual_done}")
        lines.append(f"  - manual_review_pending={manual_pending}")
    lines.append(f"- 备注：{notes or '无'}")
    lines.append("")
    return "\n".join(lines)


def append_csv_row(
    path: Path,
    *,
    batch_name: str,
    review_date: str,
    reviewer_a: str,
    reviewer_b: str,
    eval_set_version: str,
    human_questions: int,
    human_pass: int,
    high_risk_errors: int,
    allow_release: str,
    doc_rows: int,
    web_rows: int,
    merged_rows: int,
    manual_total: int | None,
    manual_done: int | None,
    manual_pending: int | None,
    notes: str,
) -> None:
    fieldnames = [
        "batch_name",
        "review_date",
        "reviewer_a",
        "reviewer_b",
        "eval_set_version",
        "human_review_questions",
        "human_review_pass",
        "high_risk_errors",
        "allow_release",
        "document_rows",
        "web_rows",
        "merged_rows",
        "manual_review_total",
        "manual_review_done",
        "manual_review_pending",
        "notes",
    ]
    row = {
        "batch_name": batch_name,
        "review_date": review_date,
        "reviewer_a": reviewer_a,
        "reviewer_b": reviewer_b,
        "eval_set_version": eval_set_version,
        "human_review_questions": str(human_questions),
        "human_review_pass": str(human_pass),
        "high_risk_errors": str(high_risk_errors),
        "allow_release": allow_release,
        "document_rows": str(doc_rows),
        "web_rows": str(web_rows),
        "merged_rows": str(merged_rows),
        "manual_review_total": "" if manual_total is None else str(manual_total),
        "manual_review_done": "" if manual_done is None else str(manual_done),
        "manual_review_pending": "" if manual_pending is None else str(manual_pending),
        "notes": notes or "",
    }

    path.parent.mkdir(parents=True, exist_ok=True)
    file_exists = path.exists()
    with path.open("a", encoding="utf-8-sig", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        if not file_exists:
            writer.writeheader()
        writer.writerow(row)


def main() -> int:
    args = parse_args()
    run_report_path = Path(args.run_report)
    if not run_report_path.exists():
        raise SystemExit(f"run_report not found: {run_report_path}")

    run_report = load_run_report(run_report_path)
    doc_rows, web_rows, merged_rows = extract_counts(run_report)

    manual_total = manual_done = manual_pending = None
    if args.manual_review:
        manual_path = Path(args.manual_review)
        if not manual_path.exists():
            raise SystemExit(f"manual_review not found: {manual_path}")
        manual_total, manual_done, manual_pending = summarize_manual_review(manual_path)

    review_date = datetime.now().strftime("%Y-%m-%d")
    block = build_block(
        batch_name=args.batch_name,
        review_date=review_date,
        reviewer_a=args.reviewer_a,
        reviewer_b=args.reviewer_b,
        eval_set_version=args.eval_set_version,
        human_questions=args.human_review_questions,
        human_pass=args.human_review_pass,
        high_risk_errors=args.high_risk_errors,
        allow_release=args.allow_release,
        notes=args.notes,
        doc_rows=doc_rows,
        web_rows=web_rows,
        merged_rows=merged_rows,
        manual_total=manual_total,
        manual_done=manual_done,
        manual_pending=manual_pending,
    )

    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    if output.exists():
        existing = output.read_text(encoding="utf-8")
        if not existing.endswith("\n"):
            existing += "\n"
        output.write_text(existing + "\n" + block, encoding="utf-8")
    else:
        output.write_text(block, encoding="utf-8")

    csv_output = Path(args.csv_output)
    append_csv_row(
        csv_output,
        batch_name=args.batch_name,
        review_date=review_date,
        reviewer_a=args.reviewer_a,
        reviewer_b=args.reviewer_b,
        eval_set_version=args.eval_set_version,
        human_questions=args.human_review_questions,
        human_pass=args.human_review_pass,
        high_risk_errors=args.high_risk_errors,
        allow_release=args.allow_release,
        doc_rows=doc_rows,
        web_rows=web_rows,
        merged_rows=merged_rows,
        manual_total=manual_total,
        manual_done=manual_done,
        manual_pending=manual_pending,
        notes=args.notes,
    )

    if not args.skip_gate_flag:
        gate_flag = Path(args.gate_flag)
        gate_flag.parent.mkdir(parents=True, exist_ok=True)
        enabled_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        gate_flag.write_text(
            f"enabled_at={enabled_at}\nreason=first_release_review_entry_created\n",
            encoding="utf-8",
        )
        print(f"Release gate flag enabled: {gate_flag}")

    print(f"Appended release review entry to: {output}")
    print(f"Appended release review csv row to: {csv_output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
